// Catalogue of optical phenomena and real-world imaging challenges.
// Entry: [name, lab id | null, domains ('p' photo, 'v' video, 's' space), description, TeX equation]
const r = String.raw;

export const GROUPS = [
  {
    title: 'Geometrical image formation',
    intro: 'First-order (paraxial) optics: where images form, how big they are, and how much light reaches them.',
    items: [
      ['Refraction (Snell\'s law)', 'raytracer', 'pvs', 'Light changes direction at an index boundary; the basis of every lens.', r`n_1\sin\theta_1 = n_2\sin\theta_2`],
      ['Thin-lens imaging', 'dof', 'pvs', 'Object and image distances are conjugate; lateral magnification is their ratio.', r`\tfrac1{s}+\tfrac1{s'}=\tfrac1f,\quad m=-\tfrac{s'}{s}`],
      ['Thick lenses & cardinal points', 'raytracer', 'pvs', 'Real lenses act as a thin lens placed at two principal planes; found from the system matrix.', r`f=-1/M_{21},\ \ \text{BFD}=-M_{11}/M_{21}`],
      ['Entrance & exit pupils', 'raytracer', 'pvs', 'Images of the aperture stop seen from object and image space; they set the cone of light and the perspective centre.', r`z_{EP}=B/A,\ \ r_{EP}=r_\text{stop}/A`],
      ['f-number & numerical aperture', 'sensor', 'pvs', 'Ratio of focal length to entrance-pupil diameter; image irradiance scales as 1/N².', r`N=\frac{f}{D}\approx\frac{1}{2\,\mathrm{NA}'}`],
      ['Étendue & brightness theorem', 'foundations', 'pvs', 'The product of area and solid angle cannot decrease; no optic can brighten a source\'s image.', r`G=n^2A\Omega,\quad L/n^2=\text{const}`],
      ['Field of view & crop factor', 'sensor', 'pv', 'Sensor size and focal length set the angle of view; crop factor rescales equivalents.', r`\mathrm{FOV}=2\arctan\frac{d}{2f},\ k=\frac{43.27}{d}`],
      ['Depth of field', 'dof', 'pv', 'Range of object distances whose blur stays below the circle of confusion.', r`D_{N,F}=\frac{sf^2}{f^2\pm Nc(s-f)}`],
      ['Hyperfocal distance', 'dof', 'pv', 'Focus distance that puts the far limit at infinity.', r`H=\frac{f^2}{Nc}+f`],
      ['Depth of focus', 'dof', 'pvs', 'Tolerance on sensor position: image-side counterpart of depth of field.', r`\Delta z'=\pm Nc(1+m)`],
      ['Perspective & compression', 'perspective', 'pv', 'Relative sizes depend on distance ratios only; focal length just crops.', r`\frac{y_1'}{y_2'}=\frac{y_1}{y_2}\cdot\frac{z_2}{z_1}`],
      ['Projection mappings (fisheye)', 'projection', 'pvs', 'How field angle maps to image height: gnomonic, stereographic, equidistant, equisolid, orthographic.', r`r=f\tan\theta,\ 2f\tan\tfrac\theta2,\ f\theta,\ 2f\sin\tfrac\theta2`],
      ['Tilt (Scheimpflug) & hinge rule', 'tiltshift', 'pv', 'Tilting the lens rotates the plane of focus about a hinge line.', r`J=\frac{f}{\sin\alpha}`],
      ['Shift & keystone correction', 'tiltshift', 'p', 'A level sensor keeps verticals parallel; shifting recentres the frame in a larger image circle.', r`\varnothing_\text{circle}\ge2\sqrt{(w/2)^2+(h/2+s)^2}`],
      ['Bellows factor & pupil magnification', 'foundations', 'p', 'At close focus the effective f-number grows, darkening the image.', r`N_w=N\left(1+\frac{|m|}{m_p}\right)`],
      ['Focus breathing', null, 'v', 'Field of view changes with focus distance because internal focusing changes the effective focal length; critical for cinema lenses.', r`m=\frac{f}{s-f}\ \Rightarrow\ \mathrm{FOV}(s)`],
      ['Telecentricity', 'vignetting', 'pvs', 'Chief rays parallel to the axis in object or image space: magnification independent of defocus, uniform pixel illumination.', r`z_{XP}\to\infty\Rightarrow\theta_\text{CRA}=0`],
    ],
  },
  {
    title: 'Monochromatic aberrations',
    intro: 'Departures from perfect imaging for a single wavelength: the terms of the wave-aberration expansion.',
    items: [
      ['Spherical aberration', 'raytracer', 'pvs', 'Marginal and paraxial rays focus at different distances; halo and focus shift.', r`W_{040}\rho^4,\quad Z_{11}=\sqrt5(6\rho^4-6\rho^2+1)`],
      ['Coma', 'zernike', 'pvs', 'Off-axis comet-shaped blur from a field-dependent magnification of pupil zones.', r`W_{131}H\rho^3\cos\phi`],
      ['Astigmatism', 'zernike', 'pvs', 'Tangential and sagittal fans focus at different distances: line foci.', r`W_{222}H^2\rho^2\cos^2\phi`],
      ['Field curvature (Petzval)', 'raytracer', 'pvs', 'The natural image surface is curved; flat sensors need flattened designs.', r`\frac{1}{R_P}=-n'\sum_k\frac{\phi_k}{n_kn_k'}`],
      ['Distortion', 'perspective', 'pvs', 'Field-dependent magnification: barrel, pincushion, moustache.', r`x_d=x(1+k_1r^2+k_2r^4+k_3r^6)`],
      ['Decentering & tilt (tolerances)', 'perspective', 'pvs', 'Manufacturing errors add asymmetric coma, astigmatism and tangential distortion.', r`\Delta x=2p_1xy+p_2(r^2+2x^2)`],
      ['Focus shift on stopping down', 'raytracer', 'p', 'Residual spherical aberration moves best focus as the aperture changes.', r`\Delta z_\text{best}(N)\propto W_{040}/N^2`],
      ['Higher-order aberrations', 'zernike', 'pvs', 'Secondary spherical, oblique spherical and elliptical coma dominate fast and wide lenses.', r`W_{060}\rho^6,\ W_{240}H^2\rho^4,\ W_{331}H^3\rho^3\cos\phi`],
      ['Pupil aberration', 'vignetting', 'p', 'The entrance pupil itself is aberrated: it grows and tilts off-axis, beating cos⁴ in wide-angle lenses.', r`E\propto\cos^n\theta,\ n<4`],
      ['Wavefront error & Strehl ratio', 'zernike', 'pvs', 'RMS wavefront error predicts peak intensity relative to perfection.', r`S\approx e^{-(2\pi\sigma_W/\lambda)^2}`],
      ['Transverse ray aberration', 'raytracer', 'pvs', 'Spot positions are gradients of the wave aberration.', r`\varepsilon_y=-\frac{R}{n'}\frac{\partial W}{\partial y_p}`],
      ['Aspheric surfaces', null, 'pvs', 'Conic and polynomial surfaces cancel aberrations with fewer elements; also cause onion-ring bokeh.', r`z=\frac{cr^2}{1+\sqrt{1-(1+k)c^2r^2}}+\sum a_ir^{2i}`],
    ],
  },
  {
    title: 'Chromatic effects',
    intro: 'Consequences of dispersion: the refractive index depends on wavelength.',
    items: [
      ['Dispersion (Sellmeier)', 'chromatic', 'pvs', 'Refractive index falls with wavelength between UV and IR resonances.', r`n^2-1=\sum_i\frac{B_i\lambda^2}{\lambda^2-C_i}`],
      ['Abbe number', 'chromatic', 'pvs', 'Single-number measure of dispersion in the visible.', r`V_d=\frac{n_d-1}{n_F-n_C}`],
      ['Longitudinal chromatic aberration (LoCA)', 'chromatic', 'pv', 'Focus varies with wavelength: magenta/green fringes out of focus.', r`\Delta f\approx-\frac{f}{V}`],
      ['Lateral chromatic aberration (LaCA)', 'chromatic', 'pv', 'Magnification varies with wavelength: radial colour fringes towards the corners.', r`m(\lambda)=m_d\left[1+\kappa\frac{n(\lambda)-n_d}{n_F-n_C}\right]`],
      ['Achromat condition', 'chromatic', 'pvs', 'Two glasses bring two wavelengths to one focus.', r`\frac{\phi_1}{V_1}+\frac{\phi_2}{V_2}=0`],
      ['Secondary spectrum & apochromats', 'chromatic', 'ps', 'Residual focus spread of achromats; needs anomalous-dispersion glass to remove.', r`\frac{\delta f}{f}=\frac{P_1-P_2}{V_1-V_2}`],
      ['Spherochromatism', 'raytracer', 'p', 'Spherical aberration that differs by wavelength; coloured halos around highlights.', r`W_{040}(\lambda)`],
      ['Purple fringing', 'chromatic', 'p', 'Violet halos at high-contrast edges from LoCA at short wavelengths plus sensor blooming and microlens leakage.', r`\Delta f(\lambda<450\,\text{nm})`],
      ['Atmospheric dispersion', 'seeing', 's', 'Air refracts blue more than red; stars become spectra near the horizon. Corrected by ADC prisms.', r`R(\lambda)\approx(n(\lambda)-1)\tan z`],
      ['Rainbows, prisms & halos', null, 'p', 'Dispersion in droplets and ice crystals; minimum deviation sets the 42° rainbow and 22° halo.', r`D_\text{min}=2\arcsin\left(n\sin\tfrac A2\right)-A`],
    ],
  },
  {
    title: 'Diffraction and wave optics',
    intro: 'The wave nature of light: the ultimate limit on sharpness and the source of stars, rings and speckle.',
    items: [
      ['Airy disk', 'psf', 'pvs', 'Fraunhofer pattern of a circular pupil; sets the diffraction limit.', r`I(v)=\left[\frac{2J_1(v)}{v}\right]^2,\ r_1=1.22\lambda N`],
      ['Rayleigh, Sparrow & Dawes limits', 'mtf', 'ps', 'Conventional two-point resolution criteria.', r`\theta_R=1.22\frac{\lambda}{D},\ \theta_S=0.947\frac{\lambda}{D}`],
      ['Diffraction-limited aperture', 'sensor', 'p', 'The f-number beyond which the Airy disk outgrows the pixels.', r`N_\text{DLA}\approx\frac{p}{1.22\lambda}`],
      ['Diffraction spikes (spiders, struts)', 'psf', 'ps', 'Straight obstructions diffract light perpendicular to themselves.', r`\tilde P\ \text{of a line}\ \propto\ \delta(f_\parallel)\,\mathrm{sinc}(wf_\perp)`],
      ['Sunstars (iris starbursts)', 'flare', 'p', 'Polygonal irises produce n spikes (even blade count) or 2n (odd).', r`N_\text{spikes}=n\ (\text{even}),\ 2n\ (\text{odd})`],
      ['Segmented-mirror PSF', 'psf', 's', 'Segment shape times array factor: JWST\'s hexagonal spikes and snowflake.', r`\mathrm{PSF}=|\tilde p|^2\left|\sum_je^{-i2\pi\mathbf f\cdot\mathbf r_j}\right|^2`],
      ['Central obstruction', 'psf', 'ps', 'Annular pupils narrow the core but move energy into rings.', r`I\propto\left[\tfrac{2J_1(v)}{v}-\varepsilon^2\tfrac{2J_1(\varepsilon v)}{\varepsilon v}\right]^2`],
      ['Optical transfer function (MTF)', 'mtf', 'pvs', 'Contrast transfer vs spatial frequency; autocorrelation of the pupil.', r`\mathrm{MTF}(\hat\nu)=\tfrac2\pi[\arccos\hat\nu-\hat\nu\sqrt{1-\hat\nu^2}]`],
      ['Diffraction cut-off frequency', 'mtf', 'pvs', 'No detail finer than this passes any lens.', r`\nu_c=\frac{1}{\lambda N}`],
      ['Defocus OTF & spurious resolution', 'mtf', 'pv', 'Strong defocus makes the OTF negative: contrast reversal.', r`H(\nu)=\frac{2J_1(\pi c\nu)}{\pi c\nu}`],
      ['Fresnel diffraction & defocus rings', 'psf', 'ps', 'Near-field patterns; out-of-focus stars show concentric rings.', r`N_F=\frac{a^2}{\lambda z}`],
      ['Apodisation', 'bokeh', 'ps', 'Tapered pupil transmission suppresses rings (STF lenses, coronagraphs).', r`P(\rho)=T(\rho)\,\mathrm{circ}(\rho)`],
      ['Babinet\'s principle', 'psf', 's', 'Complementary screens give identical diffraction patterns away from the forward beam.', r`U_\text{aperture}+U_\text{screen}=U_0`],
      ['Coherence & speckle', 'seeing', 'ps', 'Coherent light interferes randomly off rough surfaces or through turbulence.', r`A_c\approx\frac{\lambda^2}{\Omega_s}\ \ (\text{Van Cittert–Zernike})`],
      ['Thin-film interference', 'flare', 'pvs', 'Reflections from film boundaries interfere: coatings, oil slicks, Newton\'s rings.', r`2n d\cos\theta=m\lambda`],
    ],
  },
  {
    title: 'Radiometry and illumination',
    intro: 'How much light arrives where, and why the corners are darker.',
    items: [
      ['Camera equation', 'foundations', 'pvs', 'Image irradiance from scene radiance, f-number and transmission.', r`E=\frac{\pi TL}{4N^2}\cos^4\theta`],
      ['Exposure value', 'noise', 'pv', 'Logarithmic exposure scale combining aperture and time.', r`\mathrm{EV}=\log_2\frac{N^2}{t}`],
      ['T-stops', 'flare', 'v', 'Transmission-corrected f-number used in cinema.', r`T=\frac{N}{\sqrt{\tau}}`],
      ['Natural vignetting (cos⁴)', 'vignetting', 'pvs', 'Oblique bundles are dimmer through projection and distance.', r`E(\theta)=E_0\cos^4\theta`],
      ['Mechanical vignetting', 'vignetting', 'p', 'Barrel rims clip oblique bundles; cat\'s-eye bokeh.', r`V=\frac{A(\text{pupil}\cap\text{rims})}{A_\text{pupil}}`],
      ['Pixel vignetting', 'vignetting', 'pv', 'Microlens acceptance limits steep chief rays.', r`\theta_\text{CRA}=\arctan\frac{h}{z_{XP}}`],
      ['Inverse-square law', null, 'pvs', 'Irradiance from a point source falls with distance squared; flash guide numbers.', r`E=\frac{I}{d^2},\quad \mathrm{GN}=dN`],
      ['Lambertian reflection', null, 'pv', 'Matte surfaces look equally bright from all angles.', r`L=\frac{\rho E}{\pi}`],
      ['Surface-brightness conservation', 'lensing', 's', 'Extended sources keep their surface brightness through optics and gravitational lenses.', r`I_\nu/\nu^3=\text{const}`],
      ['Reciprocity failure', null, 'p', 'Film loses sensitivity in very long exposures (Schwarzschild effect).', r`H_\text{eff}=I\,t^p,\ p<1`],
      ['Flat-field calibration', 'vignetting', 's', 'Divide by an image of a uniform source to remove vignetting and PRNU.', r`I_\text{cal}=\frac{I-D}{F-D}\langle F-D\rangle`],
    ],
  },
  {
    title: 'Stray light',
    intro: 'Light that reaches the sensor by unintended paths.',
    items: [
      ['Fresnel reflection', 'flare', 'pvs', 'Each uncoated glass–air surface reflects about 4 %.', r`R=\left(\frac{n_1-n_2}{n_1+n_2}\right)^2`],
      ['Ghost images', 'flare', 'pvs', 'Double reflections form defocused aperture images along the line through the source.', r`N_\text{ghost}=\frac{k(k-1)}{2}`],
      ['Anti-reflection coatings', 'flare', 'pvs', 'Thin-film interference cancels reflection; multilayers and nanostructures broaden it.', r`n_c=\sqrt{n_0n_s},\ d=\frac{\lambda}{4n_c}`],
      ['Veiling glare', 'flare', 'pv', 'Scattered light lifts shadows and lowers contrast.', r`C'=\frac{C}{1+g/L_\text{mean}}`],
      ['Sensor (red-dot) flare', null, 'p', 'The sensor\'s periodic microstructure diffracts light back to the lens and onto the sensor again.', r`p\sin\theta_m=m\lambda`],
      ['Filter ghosts', 'flare', 'pv', 'Flat filters in front of the lens create near-in-focus ghosts of bright sources.', r`R_\text{filter}^2`],
      ['Surface-roughness scatter', null, 'ps', 'Micro-roughness scatters a fraction of light set by RMS height.', r`\mathrm{TIS}\approx\left(\frac{4\pi\sigma\cos\theta}{\lambda}\right)^2`],
      ['Baffles & stray-light suppression', 'telescope', 's', 'Vanes, black coatings and field stops block unintended paths.', r`\mathrm{PST}(\theta)=\frac{E_\text{det}(\theta)}{E_\text{in}}`],
    ],
  },
  {
    title: 'Polarisation',
    intro: 'The vector nature of light, from glare control to telescope calibration.',
    items: [
      ['Brewster\'s angle', 'flare', 'p', 'p-polarised light is not reflected at this angle.', r`\tan\theta_B=\frac{n_2}{n_1}`],
      ['Malus\'s law (polarisers)', null, 'p', 'Transmission through a linear polariser.', r`I=I_0\cos^2\theta`],
      ['Sky polarisation', null, 'p', 'Rayleigh-scattered skylight is polarised most strongly 90° from the Sun.', r`P(\Theta)=\frac{\sin^2\Theta}{1+\cos^2\Theta}`],
      ['Birefringence', 'sampling', 'p', 'Two refractive indices split rays; used in OLPFs and waveplates.', r`d=t\,\frac{n_e^2-n_o^2}{2n_en_o}`],
      ['Stress birefringence', null, 'ps', 'Mechanical stress makes glass birefringent, degrading imaging and polarimetry.', r`\Delta n=K\sigma`],
      ['Polarisation aberrations', null, 's', 'Coatings and fold mirrors introduce retardance that distorts the PSF for each polarisation.', r`\mathbf J(\rho,\theta)\ \text{(Jones pupil)}`],
    ],
  },
  {
    title: 'Sensors, sampling and noise',
    intro: 'Turning photons into numbers: discrete in space, time and charge.',
    items: [
      ['Nyquist sampling & aliasing', 'sampling', 'pvs', 'Detail above half the sampling rate folds back to lower frequencies.', r`f_a=|f-kf_s|,\ \nu_N=\frac{1}{2p}`],
      ['Moiré', 'sampling', 'pv', '2-D aliasing of fine periodic patterns into large false patterns.', r`\mathbf k_\text{moiré}=\mathbf k-\mathbf G`],
      ['Bayer CFA & false colour', 'sampling', 'pv', 'Red and blue are sampled at half rate, so luminance detail aliases into colour.', r`\nu_{N,R/B}=\frac{1}{4p}`],
      ['Optical low-pass filter', 'sampling', 'pv', 'Birefringent plates blur by one pixel to suppress aliasing.', r`\mathrm{MTF}=|\cos\pi d\nu|`],
      ['Pixel aperture & fill factor', 'mtf', 'pvs', 'Integration over the pixel area acts as a sinc filter.', r`\mathrm{MTF}_\text{px}=|\mathrm{sinc}(a\nu)|`],
      ['Photon shot noise', 'noise', 'pvs', 'Poisson statistics of light: the fundamental noise floor.', r`\sigma=\sqrt{\bar n},\ \mathrm{SNR}=\sqrt{\bar n}`],
      ['Read noise', 'noise', 'pvs', 'Electronic noise added at readout; dominates in the shadows.', r`\sigma_r=\sqrt{\sigma_\text{pre}^2+(\sigma_\text{post}/g)^2}`],
      ['Dark current & hot pixels', 'noise', 'ps', 'Thermally generated charge, doubling roughly every 6–7 °C.', r`D(T)\propto T^{3/2}e^{-E_g/2kT}`],
      ['Fixed-pattern noise (PRNU/DSNU)', 'noise', 'ps', 'Pixel-to-pixel gain and offset variations.', r`\sigma_\text{PRNU}=P\,\bar n`],
      ['Full-well & dynamic range', 'noise', 'pvs', 'Ratio of the largest to smallest measurable signal.', r`\mathrm{DR}=\log_2\frac{n_\text{FWC}}{\sigma_r}`],
      ['ISO & ISO invariance', 'noise', 'pv', 'Analogue gain changes clipping and downstream noise, not photon count.', r`\text{ISO}\propto g`],
      ['Quantisation', 'noise', 'pvs', 'ADC step noise.', r`\sigma_q=\frac{q}{\sqrt{12}}`],
      ['Quantum efficiency', 'noise', 'pvs', 'Fraction of photons converted to electrons; spectral and angular.', r`\eta(\lambda)=\frac{n_e}{n_\gamma}`],
      ['Blooming & smear', null, 'ps', 'Excess charge spills into neighbours or along columns (CCD).', r`n>n_\text{FWC}`],
      ['Pixel crosstalk', 'vignetting', 'p', 'Light or charge leaks into adjacent pixels at steep angles, desaturating colour.', r`\chi(\theta_\text{CRA})`],
      ['Cover-glass aberration', 'raytracer', 'p', 'The sensor stack is a plane-parallel plate that adds spherical aberration to fast lenses.', r`\Delta z=t\left(1-\frac1n\right)`],
      ['Demosaicing', 'sampling', 'pv', 'Interpolating full colour from a mosaic; algorithms trade sharpness and artefacts.', r`\hat G=\hat G_\text{bilinear}+\tfrac12\,\Delta^2_{R}\ \ (\text{Malvar–He–Cutler})`],
      ['Pixel shift & drizzle', 'telescope', 'ps', 'Sub-pixel dithered frames recover resolution beyond the pixel grid.', r`p_\text{eff}=p/n\ \ (n\times n\ \text{sub-pixel dither})`],
    ],
  },
  {
    title: 'Time and motion',
    intro: 'Sampling the time axis: blur, shear and aliasing in moving images.',
    items: [
      ['Motion blur', 'motion', 'pv', 'Image motion during exposure smears detail.', r`b=v\,t_e`],
      ['Shutter angle', 'motion', 'v', 'Cinema exposure as a fraction of the frame period; 180° rule.', r`t_e=\frac{\theta}{360^\circ}\frac{1}{f_\text{fps}}`],
      ['Rolling-shutter distortion', 'motion', 'pv', 'Rows captured at different times shear and bend fast motion.', r`t(y)=t_0+\frac{y}{H}T_\text{read}`],
      ['Flicker banding', 'motion', 'pv', 'Mains or PWM light modulation integrated per row.', r`I(y)=\tfrac1{t_e}\int_{t(y)}^{t(y)+t_e}L(t)\,dt`],
      ['Wagon-wheel effect', 'motion', 'v', 'Temporal aliasing makes wheels stop or reverse.', r`f_\text{app}=f-f_s\,\mathrm{round}(f/f_s)`],
      ['Camera shake', null, 'pv', 'Angular jitter blurs in proportion to focal length; the reciprocal rule.', r`t\lesssim\frac{1}{f_\text{eq}}`],
      ['Image stabilisation', null, 'pvs', 'Moving elements or sensor counter angular motion; fine-guidance in telescopes.', r`\delta y=f\,\delta\theta`],
      ['Pan judder', 'motion', 'v', 'Low frame rates strobe during pans; limits on pan speed.', r`v_\text{max}\approx\frac{W}{7\,\text{s}}`],
      ['Pointing jitter (space)', null, 's', 'Line-of-sight jitter broadens the PSF; JWST ≈ 1 mas.', r`\mathrm{PSF}\ast\mathcal N(0,\sigma_j^2)`],
    ],
  },
  {
    title: 'Atmosphere and environment',
    intro: 'What happens to light between the scene and the lens.',
    items: [
      ['Astronomical seeing', 'seeing', 'ps', 'Turbulence blurs to ~λ/r₀ regardless of aperture.', r`\mathrm{FWHM}\approx0.98\frac{\lambda}{r_0},\ r_0\propto\lambda^{6/5}`],
      ['Kolmogorov turbulence', 'seeing', 's', 'Power-law phase spectrum of atmospheric turbulence.', r`\Phi_\phi(\kappa)=0.023\,r_0^{-5/3}\kappa^{-11/3}`],
      ['Scintillation (twinkling)', 'seeing', 'ps', 'Intensity fluctuations from high-altitude turbulence; planets twinkle less.', r`\sigma_I^2\propto D^{-7/3}h^2X^3`],
      ['Adaptive optics', 'seeing', 's', 'Wavefront sensing and deformable mirrors restore the diffraction limit.', r`\sigma^2=0.28(d/r_0)^{5/3}+(\tau/\tau_0)^{5/3}`],
      ['Isoplanatic angle', 'seeing', 's', 'Field over which an AO correction remains valid.', r`\theta_0\approx0.314\,\frac{r_0}{\bar h}`],
      ['Lucky imaging & speckle interferometry', 'seeing', 'ps', 'Short exposures freeze turbulence; select or Fourier-combine them.', r`t\ll\tau_0=0.314\,\frac{r_0}{v}`],
      ['Atmospheric refraction', null, 's', 'Objects appear higher near the horizon.', r`R\approx(n-1)\tan z`],
      ['Extinction & airmass', null, 'ps', 'Atmospheric absorption and scattering dim sources with zenith angle.', r`m=m_0+kX,\ X\approx\sec z`],
      ['Aerial perspective & haze', 'dof', 'pv', 'Rayleigh and Mie scattering add airlight and reduce contrast with distance.', r`C(d)=C_0e^{-\beta d},\ \beta_R\propto\lambda^{-4}`],
      ['Heat shimmer & mirages', null, 'pv', 'Ground-level index gradients bend rays and distort distant scenes.', r`\frac{d}{ds}\left(n\frac{d\mathbf r}{ds}\right)=\nabla n`],
      ['Sky background & light pollution', null, 'ps', 'Scattered artificial light and airglow set the faintest detectable surface brightness.', r`\mathrm{SNR}=\frac{S}{\sqrt{S+B\,\Omega+\sigma_r^2}}`],
    ],
  },
  {
    title: 'Space telescopes and astronomy',
    intro: 'Challenges unique to observatories above (or fighting) the atmosphere.',
    items: [
      ['Diffraction-limited space imaging', 'telescope', 's', 'Without the atmosphere, resolution is λ/D at every wavelength.', r`\theta=1.22\lambda/D`],
      ['Segment phasing', 'zernike', 's', 'Aligning mirror segments to nanometres via dispersed fringes and phase retrieval.', r`\sigma_\text{piston}\ll\lambda/20`],
      ['Phase retrieval', 'zernike', 's', 'Inferring the wavefront from defocused PSFs (Gerchberg–Saxton style).', r`\min_W\sum_k\big||\mathcal F\{Pe^{i(W+\delta_k)}\}|^2-I_k\big|^2`],
      ['Coronagraphy', 'telescope', 's', 'Suppressing starlight by 10⁻⁶–10⁻¹⁰ to image exoplanets.', r`E_3=\mathcal F\{L\,\mathcal F^{-1}[(1-M)\mathcal F\{P\}]\}`],
      ['Speckle floor & wavefront stability', 'telescope', 's', 'Picometre-level wavefront ripples create planet-like speckles.', r`C\approx(\pi h/\lambda)^2`],
      ['Thermal emission & cryogenics', 'telescope', 's', 'Warm optics glow in the infrared, so IR telescopes must be cold.', r`B_\lambda(T)=\frac{2hc^2}{\lambda^5}\frac{1}{e^{hc/\lambda kT}-1}`],
      ['Undersampling', 'telescope', 's', 'Pixels larger than λ/2D lose resolution; recovered by dithering.', r`p\le\frac{\lambda}{2D}`],
      ['Plate scale & astrometry', 'telescope', 's', 'Angle per millimetre on the focal plane; distortion solutions for precise positions.', r`s=\frac{206\,265''}{f}`],
      ['Sensitivity scaling', 'telescope', 's', 'Background-limited point-source exposure time falls steeply with aperture.', r`t\propto D^{-4}`],
      ['Orbital focus breathing', null, 's', 'Thermal cycles change the telescope\'s length and focus each orbit (HST ≈ µm).', r`\Delta z=\alpha L\,\Delta T`],
      ['Cosmic rays & persistence', 'noise', 's', 'Particle hits and latent charge in IR arrays; rejected by up-the-ramp sampling.', r`\hat f=\frac{\sum(t_i-\bar t)(S_i-\bar S)}{\sum(t_i-\bar t)^2}`],
      ['Zodiacal light', null, 's', 'Sunlight scattered by interplanetary dust sets the background for space telescopes.', r`B_\text{zodi}(\lambda,\epsilon)`],
      ['Gravitational lensing', 'lensing', 's', 'Mass bends light into arcs, rings and multiple images.', r`\boldsymbol\beta=\boldsymbol\theta-\boldsymbol\alpha(\boldsymbol\theta)`],
      ['Einstein radius & mass', 'lensing', 's', 'Ring size measures the enclosed mass.', r`\theta_E=\sqrt{\frac{4GM}{c^2}\frac{D_{ls}}{D_lD_s}}`],
      ['Cosmological redshift', 'telescope', 's', 'Distant galaxies\' light is stretched into the infrared: JWST\'s raison d\'être.', r`\lambda_\text{obs}=(1+z)\lambda_\text{emit}`],
    ],
  },
  {
    title: 'Lens design and manufacturing',
    intro: 'Engineering choices that shape every image.',
    items: [
      ['Retrofocus & telephoto designs', 'raytracer', 'pv', 'Negative-front or negative-rear groups decouple back focus from focal length.', r`\text{telephoto ratio}=\frac{L}{f}<1`],
      ['Double-Gauss symmetry', 'raytracer', 'pv', 'Near-symmetric layouts cancel odd aberrations (coma, distortion, lateral colour).', r`W_{131},W_{311},\Delta m(\lambda)\to0`],
      ['Bending & shape factor', 'raytracer', 'p', 'Lens shape at fixed power controls spherical aberration and coma.', r`q=\frac{R_2+R_1}{R_2-R_1}`],
      ['ED & fluorite elements', 'chromatic', 'ps', 'Anomalous partial dispersion enables apochromatic correction.', r`\Delta P_{g,F}>0`],
      ['Floating elements', null, 'p', 'Groups move differently when focusing to keep aberrations corrected at close range.', r`W(s)\approx\text{const}`],
      ['Thermal focus shift', null, 'ps', 'Index and housing expand with temperature.', r`\frac{df}{dT}=-f\left(\frac{dn/dT}{n-1}-\alpha\right)`],
      ['Anamorphic lenses', null, 'v', 'Cylindrical optics squeeze the image; oval bokeh and horizontal streak flares.', r`f_x\neq f_y,\ \text{squeeze}=f_y/f_x`],
      ['Parfocal zooms', null, 'v', 'Focus stays fixed while zooming; essential for broadcast and cinema.', r`\partial z_\text{img}/\partial f=0`],
      ['Tolerancing & yield', 'raytracer', 'pvs', 'Statistical sensitivity of performance to fabrication and assembly errors.', r`\sigma_\text{perf}^2=\sum_i\left(\frac{\partial M}{\partial x_i}\right)^2\sigma_{x_i}^2`],
    ],
  },
  {
    title: 'Rendering and perception',
    intro: 'How optical properties become the "look" of an image.',
    items: [
      ['Bokeh', 'bokeh', 'pv', 'Rendering of out-of-focus areas: pupil shape plus residual aberrations.', r`\frac{I(r)}{I_0}=\frac{1}{(1+s\rho^2)(1+3s\rho^2)}`],
      ['Swirly bokeh', 'bokeh', 'p', 'Tangentially oriented cat\'s eyes plus field curvature (Petzval lenses).', r`V_\text{mech}(\theta)`],
      ['Micro-contrast', 'mtf', 'p', 'Perceived "pop" relates to MTF at low-to-mid frequencies.', r`\mathrm{SQF}=\int\mathrm{MTF}(\nu)\,\mathrm{CSF}(\nu)\,d\ln\nu`],
      ['Circle of confusion & viewing', 'dof', 'p', 'Sharpness criterion set by eye resolution, print size and viewing distance.', r`c=\frac{d}{1500}\ \ (\approx1'\ \text{at 25 cm, }8\times10\,\text{in print})`],
      ['Colour temperature & white balance', null, 'pv', 'Illuminant spectra shift colours; cameras rescale channels.', r`T_\text{CCT}:\ (x,y)\approx\text{Planckian locus}`],
      ['Tone mapping & dynamic range', 'noise', 'pv', 'Compressing scene range into display range.', r`L_d=\frac{L}{1+L}`],
      ['Chromatic adaptation', null, 'pv', 'Von Kries scaling of cone responses to the scene illuminant.', r`\mathbf L'=\mathrm{diag}(k_L,k_M,k_S)\,\mathbf L`],
    ],
  },
];

export const COUNT = GROUPS.reduce((a, g) => a + g.items.length, 0);
